version: '3.1'
services: 
    nginx:
        restart: always
        image: nginx
        container_name: nginx
        volumes: 
            - ./conf.d:/etc/nginx/conf.d
            - ./src:/usr/shared/xmind
        ports:
            - 80:80